version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '3000:80'
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - '8000:8000'