GENDER_MAP={
    "male":0, "female":1,"other":2
}

EDUCATION_MAP={
    "Bachelor's Degree":0, "Master's Degree":1, "PhD":2,
    "Bachelor's":3, "High School":4, "Master's": 5, "phD":6
}

JOB_MAP={   
    "Software Engineer":0, 
	"Data Scientist":1, "Software Engineer Manager":2, "Data Analyst":3, 
	"Senior Project Engineer":4, "Product Manager":5, "Full Stack Engineer":6, 
	"Marketing Manager":7, "Senior Software Engineer":8, "Back end Developer":9, 
	"Front end Developer":10, "Marketing Coordinator":11, "Junior Sales Associate":12, 
	"Financial Manager":13, "Marketing Analyst":14, "Software Developer":15, 
	"Operations Manager":16, "Human Resources Manager":17, "Director of Marketing":18, 
	"Web Developer":19, "Product Designer":20, "Research Director":21, 
	"Content Marketing Manager":22, "Sales Associate":23, "Director of HR":24, 
	"Senior Product Marketing Manager":25, "Research Scientist":26, "Marketing Director":27, 
	"Sales Director":28, "Senior Data Scientist":29, "Junior HR Generalist":30, 
	"Junior Software Developer":31, "Director of Data Science":32, "Receptionist":33, 
	"Sales Manager":34, "Digital Marketing Manager":35, "Junior Marketing Manager":36, 
	"Junior Software Engineer":37, "Senior Research Scientist":38, "Human Resources Coordinator":39, 
	"Senior Human Resources Manager":40, "Junior Web Developer":41, "Senior HR Generalist":42, 
	"Junior Sales Representative":43, "Financial Analyst":44, "Sales Representative":45, 
	"Sales Executive":46, "Front End Developer":47, "Junior HR Coordinator":48, 
	"Junior Data Analyst":49, "Project Manager":50, "Graphic Designer":51, 
	"Digital Marketing Specialist":52, "Social Media Manager":53, "Director of Operations":54, 
	"Senior Business Analyst":55, "Senior Marketing Analyst":56, "Senior Marketing Manager":57, 
	"Junior Business Analyst":58, "Senior Financial Analyst":59, "Senior Project Manager":60, 
	"Junior Financial Analyst":61, "Junior Business Development Associate":62, "Senior Product Manager":63, 
	"Customer Service Representative":64, "Junior Marketing Coordinator":65, "Senior Project Coordinator":66, 
	"Senior Operations Manager":67, "Junior Operations Analyst":68, "Senior Financial Manager":69, 
	"Delivery Driver":70, "Junior Project Manager":71, "Senior Product Designer":72, 
	"Junior Marketing Specialist":73, "Senior Operations Coordinator":74, "Senior Data Engineer":75, 
	"Senior Business Development Manager":76, "Senior Marketing Specialist":77, "Junior Product Manager":78, 
	"Senior Scientist":79, "Junior Accountant":80, "Junior Marketing Analyst":81, 
	"Senior UX Designer":82, "Junior Operations Manager":83, "Juniour HR Generalist":84, 
	"Juniour HR Coordinator":85, "Senior Marketing Coordinator":86, "Senior Financial Advisor":87, 
	"Senior Data Analyst":88, "Senior HR Manager":89, "Senior Software Developer":90, 
	"Director of Finance":91, "Senior IT Consultant":92, "Junior Business Operations Analyst":93, 
	"Senior Sales Representative":94, "Event Coordinator":95, "Customer Service Manager":96, 
	"HR Manager":97, "Senior Manager":98, "Senior Engineer":99, 
	"Recruiter":100, "Director of Engineering":101, "Senior Sales Manager":102, 
	"Director of Human Resources":103, "Senior Operations Analyst":104, "Business Analyst":105, 
	"Administrative Assistant":106, "Senior Accountant":107, "HR Generalist":108, 
	"Junior Account Manager":109, "Operations Director":110, "Customer Success Rep":111, 
	"UX Designer":112, "VP of Operations":113, "IT Support":114, 
	"Social Media Specialist":115, "Software Manager":116, "Senior Consultant":117, 
	"Director":118, "Customer Service Rep":119, "Data Entry Clerk":120, 
	"CEO":121, "Junior Developer":122, "Accountant":123, 
	"Network Engineer":124, "Copywriter":125, "Strategy Consultant":126, 
	"Account Manager":127, "Help Desk Analyst":128, "Business Development Manager":129, 
	"IT Manager":130, "VP of Finance":131, "UX Researcher":132, 
	"Business Intelligence Analyst":133, "Project Engineer":134, "Technical Writer":135, 
	"Marketing Specialist":136, "Principal Engineer":137, "Chief Data Officer":138, 
	"Digital Content Producer":139, "IT Support Specialist":140, "Chief Technology Officer":141, 
	"Senior Training Specialist":142, "Sales Operations Manager":143, "Junior Web Designer":144, 
	"Training Specialist":145, "Supply Chain Manager":146, "Principal Scientist":147, 
	"Junior Designer":148, "Financial Advisor":149, "Creative Director":150, 
	"Operations Analyst":151, "Public Relations Manager":152, "Product Marketing Manager":153, 
	"Senior Graphic Designer":154, "Software Project Manager":155, "Supply Chain Analyst":156, 
	"Customer Success Manager":157, "Technical Recruiter":158, "Human Resources Director":159, 
	"Technical Support Specialist":160, "Junior Customer Support Specialist":161, "Senior IT Support Specialist":162, 
	"Director of Sales":163, "Junior Recruiter":164, "Office Manager":165, 
	"Senior Marketing Director":166, "Junior Social Media Manager":167, "Senior Human Resources Specialist":168, 
	"Director of Sales and Marketing":169, "Senior Quality Assurance Analyst":170, "Senior IT Project Manager":171, 
	"Junior Copywriter":172, "Senior Researcher":173, "Senior Account Manager":174, 
	"Junior Data Scientist":175, "Senior Human Resources Coordinator":176, "Director of Product Management":177, 
	"Director of Human Capital":178, "Junior Advertising Coordinator":179, "Junior UX Designer":180, 
	"Senior Account Executive":181, "Director of Business Development":182, "Senior HR Specialist":183, 
	"Senior Product Development Manager":184, "Junior Operations Coordinator":185, "Junior Financial Advisor":186, 
	"Junior Research Scientist":187, "Junior Social Media Specialist":188, "Senior Software Architect":189, 
	"Developer":190, "Social M":191, "Social Media Man":192, 
	}
